"""AISkills CLI — aiskills command-line interface."""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import click
from rich import box
from rich.console import Console
from rich.table import Table

from aiskills import __version__
from aiskills.doctor import run_doctor
from aiskills.registry import SkillRegistry
from aiskills.validator import validate_all

console = Console()


def _find_skills_root() -> Path:
    """Locate the AISkills skills/ directory.

    Search order:
    1. AISKILLS_DIR environment variable
    2. The package's own skills/ directory (for development / installed package)
    3. Current working directory skills/
    """
    import os

    env_dir = os.environ.get("AISKILLS_DIR")
    if env_dir:
        return Path(env_dir) / "skills"

    # When installed as a package, skills/ lives alongside pyproject.toml
    # We walk up from this file to find the project root
    this_file = Path(__file__).resolve()
    for parent in this_file.parents:
        candidate = parent / "skills"
        if candidate.is_dir() and any(candidate.rglob("SKILL.md")):
            return candidate

    # Fallback: cwd
    return Path.cwd() / "skills"


def _find_project_root() -> Path:
    """Walk up from cwd to find a git root or pyproject.toml."""
    cwd = Path.cwd()
    for parent in [cwd, *cwd.parents]:
        if (parent / ".git").exists() or (parent / "pyproject.toml").exists():
            return parent
    return cwd


AGENTS_MD_CONTENT = f"""\
# AGENTS.md — Project Instructions for AI Coding Agents

This repository uses **AISkills** for structured AI engineering workflows.

## Before Starting Any Task

1. Read this file
2. Read `CONTEXT.md` in this repository
3. Use the `repository-discovery` skill to understand the codebase
4. Select the appropriate AISkills workflow for the task
5. Respect all human approval gates (marked ⚠️ REQUIRES APPROVAL)

## Human Approval Required

Stop and ask the human before:
- Deleting files or directories
- Modifying production configuration
- Pushing commits or publishing releases
- Changing credentials or secrets
- Running destructive database operations

## Finding Skills

```bash
aiskills list                     # All available skills
aiskills search "RAG evaluation"  # Search by keyword
aiskills info rag-evaluation      # Skill details
```

## Skill Workflows

| Task | Workflow |
|------|---------|
| New feature | feature-development workflow |
| Bug fix | bug-fixing workflow |
| RAG system | rag-development workflow |
| AI agent | agent-development workflow |
| Security audit | security-review workflow |
| Production deploy | production-readiness workflow |

*Generated by AISkills v{__version__}*
"""


@click.group()
@click.version_option(version=__version__, prog_name="aiskills")
def cli() -> None:
    """AISkills — Reusable AI Engineering Skills for Coding Agents.

    Use this CLI to discover, validate, and initialize AISkills in your project.
    """


@cli.command()
def init() -> None:
    """Initialize AISkills in the current repository.

    Creates AGENTS.md and CONTEXT.md templates in the current directory.
    """
    cwd = Path.cwd()

    created = []
    skipped = []

    # AGENTS.md
    agents_md = cwd / "AGENTS.md"
    if agents_md.exists():
        skipped.append("AGENTS.md (already exists)")
    else:
        agents_md.write_text(AGENTS_MD_CONTENT, encoding="utf-8")
        created.append("AGENTS.md")

    # CONTEXT.md — copy from the AISkills template
    context_md = cwd / "CONTEXT.md"
    if context_md.exists():
        skipped.append("CONTEXT.md (already exists)")
    else:
        # Find the template CONTEXT.md from the AISkills root
        skills_root = _find_skills_root()
        template_context = skills_root.parent / "CONTEXT.md"
        if template_context.exists():
            shutil.copy(template_context, context_md)
        else:
            # Minimal fallback if template not found
            context_md.write_text(
                "# CONTEXT.md — Fill in your project details here.\n"
                "# See https://github.com/karthikrshet/aiskills for the full template.\n",
                encoding="utf-8",
            )
        created.append("CONTEXT.md")

    console.print()
    console.print("[bold green]AISkills initialized![/bold green]")
    console.print()

    if created:
        console.print("[bold]Created:[/bold]")
        for f in created:
            console.print(f"  [green]+[/green] {f}")

    if skipped:
        console.print("[bold]Skipped:[/bold]")
        for f in skipped:
            console.print(f"  [yellow]-[/yellow] {f}")

    console.print()
    console.print("[bold]Next steps:[/bold]")
    console.print("  1. Open [cyan]CONTEXT.md[/cyan] and fill in your project details")
    console.print("  2. Run [cyan]aiskills list[/cyan] to see available skills")
    console.print("  3. Tell your AI agent: 'Read AGENTS.md and CONTEXT.md before starting'")
    console.print()


@cli.command("list")
def list_skills() -> None:
    """List all available AISkills skills."""
    skills_root = _find_skills_root()
    registry = SkillRegistry(skills_root)
    skills = registry.all()

    if not skills:
        console.print(
            f"[yellow]No skills found.[/yellow] Expected skills at: [cyan]{skills_root}[/cyan]"
        )
        console.print("Run from the AISkills repository root, or set AISKILLS_DIR.")
        return

    table = Table(
        box=box.SIMPLE,
        show_header=True,
        header_style="bold",
        pad_edge=False,
    )
    table.add_column("SKILL", style="cyan", min_width=28)
    table.add_column("CATEGORY", style="white", min_width=20)
    table.add_column("RISK", min_width=8)
    table.add_column("STATUS", min_width=12)

    risk_colors = {"low": "green", "medium": "yellow", "high": "red"}
    status_colors = {"stable": "green", "beta": "cyan", "alpha": "yellow", "experimental": "dim"}

    for skill in skills:
        risk_color = risk_colors.get(skill.risk, "white")
        status_color = status_colors.get(skill.status, "white")
        table.add_row(
            skill.name,
            skill.category,
            f"[{risk_color}]{skill.risk}[/{risk_color}]",
            f"[{status_color}]{skill.status}[/{status_color}]",
        )

    console.print()
    console.print(f"[bold]AISkills Library[/bold] ({len(skills)} skills)")
    console.print()
    console.print(table)
    console.print(f"[dim]Skills loaded from: {skills_root}[/dim]")
    console.print(
        "[dim]Use 'aiskills info <skill-name>' for details, "
        "'aiskills search <query>' to search[/dim]"
    )
    console.print()


@cli.command()
@click.argument("query")
def search(query: str) -> None:
    """Search skills by keyword or tag.

    QUERY can be any keyword, tag, or phrase. Searches skill names,
    descriptions, tags, and categories.
    """
    skills_root = _find_skills_root()
    registry = SkillRegistry(skills_root)
    results = registry.search(query)

    if not results:
        console.print(f"[yellow]No skills found matching:[/yellow] '{query}'")
        console.print("Try: [cyan]aiskills list[/cyan] to see all skills")
        return

    console.print()
    console.print(f"[bold]Search results for:[/bold] '{query}' ({len(results)} match(es))")
    console.print()

    for skill in results:
        console.print(f"  [cyan bold]{skill.name}[/cyan bold]  [dim]{skill.category}[/dim]")
        # Show first line of description
        first_line = skill.description.split("\n")[0].strip()
        if len(first_line) > 90:
            first_line = first_line[:87] + "..."
        console.print(f"    {first_line}")
        if skill.tags:
            tag_str = ", ".join(skill.tags[:5])
            console.print(f"    [dim]tags: {tag_str}[/dim]")
        console.print()


@cli.command()
@click.argument("skill_name")
def info(skill_name: str) -> None:
    """Show detailed information about a skill.

    SKILL_NAME is the unique identifier of the skill (e.g., rag-evaluation).
    """
    skills_root = _find_skills_root()
    registry = SkillRegistry(skills_root)
    skill = registry.get(skill_name)

    if skill is None:
        console.print(f"[red]Skill not found:[/red] '{skill_name}'")
        console.print("Run [cyan]aiskills list[/cyan] to see available skills.")
        sys.exit(1)

    console.print()
    console.print(
        f"[bold cyan]{skill.name}[/bold cyan]  "
        f"[dim]v{skill.version}[/dim]  "
        f"[dim]{skill.status}[/dim]"
    )
    console.print()
    console.print(f"[bold]Category:[/bold] {skill.category}")
    console.print(f"[bold]Risk:[/bold] {skill.risk}")
    console.print()
    console.print("[bold]Description:[/bold]")
    console.print(skill.description)
    console.print()

    if skill.tags:
        console.print(f"[bold]Tags:[/bold] {', '.join(skill.tags)}")

    if skill.related_skills:
        console.print(f"[bold]Related skills:[/bold] {', '.join(skill.related_skills)}")

    console.print()
    console.print(f"[dim]Skill file: {skill.path}[/dim]")
    console.print()


@cli.command()
@click.option(
    "--skills-dir",
    default=None,
    help="Path to skills directory (default: auto-detect)",
    type=click.Path(exists=False),
)
def validate(skills_dir: str | None) -> None:
    """Validate all skills against the AISkills schema.

    Checks YAML frontmatter, required Markdown sections, placeholder content,
    body length, and duplicate skill names.
    """
    if skills_dir:
        skills_root = Path(skills_dir)
    else:
        skills_root = _find_skills_root()

    console.print()
    console.print(f"[bold]Validating skills at:[/bold] {skills_root}")
    console.print()

    result = validate_all(skills_root)

    # Print errors
    for error in result.errors:
        relative = (
            error.skill_path.relative_to(skills_root)
            if skills_root in error.skill_path.parents
            else error.skill_path
        )
        console.print(f"  [red]ERROR[/red]   {relative}: {error.message}")

    # Print warnings
    for warning in result.warnings:
        relative = (
            warning.skill_path.relative_to(skills_root)
            if skills_root in warning.skill_path.parents
            else warning.skill_path
        )
        console.print(f"  [yellow]WARN[/yellow]    {relative}: {warning.message}")

    console.print()

    # Summary
    if result.is_valid:
        console.print(
            f"[bold green]PASS[/bold green] - "
            f"{result.pass_count}/{result.skill_count} skills valid"
        )
        if result.warnings:
            console.print(f"   [yellow]{len(result.warnings)} warning(s)[/yellow]")
    else:
        console.print(
            f"[bold red]FAIL[/bold red] - "
            f"{len(result.errors)} error(s), "
            f"{result.pass_count}/{result.skill_count} skills valid"
        )
        sys.exit(1)

    console.print()


@cli.command()
@click.option(
    "--project-dir",
    default=None,
    help="Project root directory (default: auto-detect)",
    type=click.Path(exists=False),
)
def doctor(project_dir: str | None) -> None:
    """Check repository health for AISkills usage.

    Verifies AGENTS.md, CONTEXT.md, skills directory, and scans skill
    files for suspicious patterns.
    """
    if project_dir:
        project_root = Path(project_dir)
    else:
        project_root = _find_project_root()

    skills_root = _find_skills_root()

    console.print()
    console.print(f"[bold]AISkills Doctor[/bold] - checking {project_root}")
    console.print()

    report = run_doctor(project_root, skills_root)

    for finding in report.findings:
        icon = {
            "OK": "[green]PASS[/green]",
            "WARNING": "[yellow]WARN[/yellow]",
            "ERROR": "[red]FAIL[/red]",
        }.get(finding.level, "    ")
        console.print(f"  {icon} [bold]{finding.check}[/bold]: {finding.message}")

    console.print()
    console.print(
        f"[bold]Summary:[/bold] "
        f"[green]{report.ok_count()} OK[/green]  "
        f"[yellow]{report.warning_count()} warnings[/yellow]  "
        f"[red]{report.error_count()} errors[/red]"
    )

    if report.has_errors:
        sys.exit(1)

    console.print()
